### ISSUE TITLE
Error triggering build

### ISSUE THREAD

**Issue by JohannesRudolph** [vito/git-branch-heads-resource#1]
I have this pipeline.yml: 

```

---
# add https://github.com/vito/git-branch-heads-resource
resource_types:
- name: git-branch-heads
  type: docker-image
  source: 
    repository: vito/git-branch-heads-resource

resources:
- name: bitbucket
  type: git-branch-heads
  source:
    uri: git@bitbucket.org:meshcloud/new-horizon.git
    branches: ['*']
    private_key: {{private-key-bitbucket-bot}}

jobs:
- name: build
  plan:
  - get: bitbucket
    trigger: true
    version: every
  - task: build
    file: bitbucket/ci/build.yml

```

When I look at my concourse web ui, I see that git-branch-heads correctly pulls in all head versions. However they all have no metadata when I click the, unlike e.g. https://ci.concourse.ci/teams/main/pipelines/wips/resources/atc

When I manually trigger a build, I get this error in concourse ui (without any further info on where it's coming from):

```
jq: error (at <stdin>:0): Cannot index object with null invalid payload (missing uri):  unexpected end of JSON input
```

I couldn't find any further info in the logs of the fly worker (stdout), but it's possible that there's some info I can provide if you let me know how to retrieve it (I'm an amateur when it comes to fly watch/hijack etc.)
